# Make sure the working directory is the repository root
# Load libraries
library(igraph)
# Read all outlinks from CSV generated by Screaming Frog SEO Spider (version 16.3)
links <- read.csv("data/all_outlinks.csv")
links <- subset(links, Type=="Hyperlink")
links <- subset(links, Follow=="true")
links <- subset(links, select=c(Source,Destination))
# Create graph
g <- graph.data.frame(links)
# Run the PageRank algorithm
pr <- page.rank(g, algo = "prpack", vids = V(g), directed = TRUE, damping = 0.85)
# Format the results
values <- data.frame(pr$vector)
values$names <- rownames(values)
row.names(values) <- NULL
values <- values[c(2,1)]
names(values)[1] <- "url"
names(values)[2] <- "pr"
# Filter domain name (puc-rio.br)
values <- values[grepl("https?:\\/\\/(.*\\.)?puc-rio\\.br.*", values$url),]
# Save results in a seperate CSV
write.csv(values, file = "data/pagerank.csv")